
DROP TABLE IF EXISTS KRONOS_FIRED_TRIGGERS;
DROP TABLE IF EXISTS KRONOS_PAUSED_TRIGGER_GRPS;
DROP TABLE IF EXISTS KRONOS_SCHEDULER_STATE;
DROP TABLE IF EXISTS KRONOS_LOCKS;
DROP TABLE IF EXISTS KRONOS_SIMPLE_TRIGGERS;
DROP TABLE IF EXISTS KRONOS_SIMPROP_TRIGGERS;
DROP TABLE IF EXISTS KRONOS_CRON_TRIGGERS;
DROP TABLE IF EXISTS KRONOS_BLOB_TRIGGERS;
DROP TABLE IF EXISTS KRONOS_TRIGGERS;
DROP TABLE IF EXISTS KRONOS_JOB_DETAILS;
DROP TABLE IF EXISTS KRONOS_CALENDARS;

CREATE TABLE KRONOS_JOB_DETAILS(
                                   SCHED_NAME VARCHAR(120) NOT NULL,
                                   JOB_NAME VARCHAR(200) NOT NULL,
                                   JOB_GROUP VARCHAR(200) NOT NULL,
                                   DESCRIPTION VARCHAR(250) NULL,
                                   JOB_CLASS_NAME VARCHAR(250) NOT NULL,
                                   IS_DURABLE BOOLEAN NOT NULL,
                                   IS_NONCONCURRENT BOOLEAN NOT NULL,
                                   IS_UPDATE_DATA BOOLEAN NOT NULL,
                                   REQUESTS_RECOVERY BOOLEAN NOT NULL,
                                   JOB_DATA BLOB NULL,
                                   PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP))
    ENGINE=InnoDB;

CREATE TABLE KRONOS_TRIGGERS (
                                 SCHED_NAME VARCHAR(120) NOT NULL,
                                 TRIGGER_NAME VARCHAR(200) NOT NULL,
                                 TRIGGER_GROUP VARCHAR(200) NOT NULL,
                                 JOB_NAME VARCHAR(200) NOT NULL,
                                 JOB_GROUP VARCHAR(200) NOT NULL,
                                 DESCRIPTION VARCHAR(250) NULL,
                                 NEXT_FIRE_TIME BIGINT(19) NULL,
                                 PREV_FIRE_TIME BIGINT(19) NULL,
                                 PRIORITY INTEGER NULL,
                                 TRIGGER_STATE VARCHAR(16) NOT NULL,
                                 TRIGGER_TYPE VARCHAR(8) NOT NULL,
                                 START_TIME BIGINT(19) NOT NULL,
                                 END_TIME BIGINT(19) NULL,
                                 CALENDAR_NAME VARCHAR(200) NULL,
                                 MISFIRE_INSTR SMALLINT(2) NULL,
                                 JOB_DATA BLOB NULL,
                                 PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
                                 FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
                                     REFERENCES KRONOS_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP))
    ENGINE=InnoDB;

CREATE TABLE KRONOS_SIMPLE_TRIGGERS (
                                        SCHED_NAME VARCHAR(120) NOT NULL,
                                        TRIGGER_NAME VARCHAR(200) NOT NULL,
                                        TRIGGER_GROUP VARCHAR(200) NOT NULL,
                                        REPEAT_COUNT BIGINT(7) NOT NULL,
                                        REPEAT_INTERVAL BIGINT(12) NOT NULL,
                                        TIMES_TRIGGERED BIGINT(10) NOT NULL,
                                        PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
                                        FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
                                            REFERENCES KRONOS_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
    ENGINE=InnoDB;

CREATE TABLE KRONOS_CRON_TRIGGERS (
                                      SCHED_NAME VARCHAR(120) NOT NULL,
                                      TRIGGER_NAME VARCHAR(200) NOT NULL,
                                      TRIGGER_GROUP VARCHAR(200) NOT NULL,
                                      CRON_EXPRESSION VARCHAR(120) NOT NULL,
                                      TIME_ZONE_ID VARCHAR(80),
                                      PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
                                      FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
                                          REFERENCES KRONOS_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
    ENGINE=InnoDB;

CREATE TABLE KRONOS_SIMPROP_TRIGGERS
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1 VARCHAR(512) NULL,
    STR_PROP_2 VARCHAR(512) NULL,
    STR_PROP_3 VARCHAR(512) NULL,
    INT_PROP_1 INT NULL,
    INT_PROP_2 INT NULL,
    LONG_PROP_1 BIGINT NULL,
    LONG_PROP_2 BIGINT NULL,
    DEC_PROP_1 NUMERIC(13,4) NULL,
    DEC_PROP_2 NUMERIC(13,4) NULL,
    BOOL_PROP_1 BOOLEAN NULL,
    BOOL_PROP_2 BOOLEAN NULL,
    TIME_ZONE_ID VARCHAR(80) NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES KRONOS_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
    ENGINE=InnoDB;

CREATE TABLE KRONOS_BLOB_TRIGGERS (
                                      SCHED_NAME VARCHAR(120) NOT NULL,
                                      TRIGGER_NAME VARCHAR(200) NOT NULL,
                                      TRIGGER_GROUP VARCHAR(200) NOT NULL,
                                      BLOB_DATA BLOB NULL,
                                      PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
                                      INDEX (SCHED_NAME,TRIGGER_NAME, TRIGGER_GROUP),
                                      FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
                                          REFERENCES KRONOS_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
    ENGINE=InnoDB;

CREATE TABLE KRONOS_CALENDARS (
                                  SCHED_NAME VARCHAR(120) NOT NULL,
                                  CALENDAR_NAME VARCHAR(200) NOT NULL,
                                  CALENDAR BLOB NOT NULL,
                                  PRIMARY KEY (SCHED_NAME,CALENDAR_NAME))
    ENGINE=InnoDB;

CREATE TABLE KRONOS_PAUSED_TRIGGER_GRPS (
                                            SCHED_NAME VARCHAR(120) NOT NULL,
                                            TRIGGER_GROUP VARCHAR(200) NOT NULL,
                                            PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP))
    ENGINE=InnoDB;

CREATE TABLE KRONOS_FIRED_TRIGGERS (
                                       SCHED_NAME VARCHAR(120) NOT NULL,
                                       ENTRY_ID VARCHAR(140) NOT NULL,
                                       TRIGGER_NAME VARCHAR(200) NOT NULL,
                                       TRIGGER_GROUP VARCHAR(200) NOT NULL,
                                       INSTANCE_NAME VARCHAR(200) NOT NULL,
                                       FIRED_TIME BIGINT(19) NOT NULL,
                                       SCHED_TIME BIGINT(19) NOT NULL,
                                       PRIORITY INTEGER NOT NULL,
                                       STATE VARCHAR(16) NOT NULL,
                                       JOB_NAME VARCHAR(200) NULL,
                                       JOB_GROUP VARCHAR(200) NULL,
                                       IS_NONCONCURRENT BOOLEAN NULL,
                                       REQUESTS_RECOVERY BOOLEAN NULL,
                                       PRIMARY KEY (SCHED_NAME,ENTRY_ID))
    ENGINE=InnoDB;

CREATE TABLE KRONOS_SCHEDULER_STATE (
                                        SCHED_NAME VARCHAR(120) NOT NULL,
                                        INSTANCE_NAME VARCHAR(200) NOT NULL,
                                        LAST_CHECKIN_TIME BIGINT(19) NOT NULL,
                                        CHECKIN_INTERVAL BIGINT(19) NOT NULL,
                                        PRIMARY KEY (SCHED_NAME,INSTANCE_NAME))
    ENGINE=InnoDB;

CREATE TABLE KRONOS_LOCKS (
                              SCHED_NAME VARCHAR(120) NOT NULL,
                              LOCK_NAME VARCHAR(40) NOT NULL,
                              PRIMARY KEY (SCHED_NAME,LOCK_NAME))
    ENGINE=InnoDB;

CREATE INDEX IDX_KRONOS_J_REQ_RECOVERY ON KRONOS_JOB_DETAILS(SCHED_NAME,REQUESTS_RECOVERY);
CREATE INDEX IDX_KRONOS_J_GRP ON KRONOS_JOB_DETAILS(SCHED_NAME,JOB_GROUP);

CREATE INDEX IDX_KRONOS_T_J ON KRONOS_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP);
CREATE INDEX IDX_KRONOS_T_JG ON KRONOS_TRIGGERS(SCHED_NAME,JOB_GROUP);
CREATE INDEX IDX_KRONOS_T_C ON KRONOS_TRIGGERS(SCHED_NAME,CALENDAR_NAME);
CREATE INDEX IDX_KRONOS_T_G ON KRONOS_TRIGGERS(SCHED_NAME,TRIGGER_GROUP);
CREATE INDEX IDX_KRONOS_T_STATE ON KRONOS_TRIGGERS(SCHED_NAME,TRIGGER_STATE);
CREATE INDEX IDX_KRONOS_T_N_STATE ON KRONOS_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_STATE);
CREATE INDEX IDX_KRONOS_T_N_G_STATE ON KRONOS_TRIGGERS(SCHED_NAME,TRIGGER_GROUP,TRIGGER_STATE);
CREATE INDEX IDX_KRONOS_T_NEXT_FIRE_TIME ON KRONOS_TRIGGERS(SCHED_NAME,NEXT_FIRE_TIME);
CREATE INDEX IDX_KRONOS_T_NFT_ST ON KRONOS_TRIGGERS(SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME);
CREATE INDEX IDX_KRONOS_T_NFT_MISFIRE ON KRONOS_TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME);
CREATE INDEX IDX_KRONOS_T_NFT_ST_MISFIRE ON KRONOS_TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_STATE);
CREATE INDEX IDX_KRONOS_T_NFT_ST_MISFIRE_GRP ON KRONOS_TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_GROUP,TRIGGER_STATE);

CREATE INDEX IDX_KRONOS_FT_TRIG_INST_NAME ON KRONOS_FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME);
CREATE INDEX IDX_KRONOS_FT_INST_JOB_REQ_RCVRY ON KRONOS_FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME,REQUESTS_RECOVERY);
CREATE INDEX IDX_KRONOS_FT_J_G ON KRONOS_FIRED_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP);
CREATE INDEX IDX_KRONOS_FT_JG ON KRONOS_FIRED_TRIGGERS(SCHED_NAME,JOB_GROUP);
CREATE INDEX IDX_KRONOS_FT_T_G ON KRONOS_FIRED_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);
CREATE INDEX IDX_KRONOS_FT_TG ON KRONOS_FIRED_TRIGGERS(SCHED_NAME,TRIGGER_GROUP);

commit;
